export const FETCH_TINYURL_PENDING = 'FETCH_TINYURL_PENDING';
export const FETCH_TINYURL_SUCCESS = 'FETCH_TINYURL_SUCCESS';
export const FETCH_TINYURL_FAILED = 'FETCH_TINYURL_FAILED';
export const RESET_STATE = 'RESET_STATE';
